FROM node:20.18.0-bookworm-slim AS base
WORKDIR /app
RUN npm install --global pnpm@9.12.0

FROM base AS deps
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
RUN pnpm install --frozen-lockfile

FROM deps AS build
ARG APP_DIR
ARG PACKAGE_NAME
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm --filter @batios/design-system clean && pnpm --filter @batios/design-system build
RUN pnpm --filter ${PACKAGE_NAME} build

FROM node:20.18.0-bookworm-slim AS runner
ARG APP_DIR
ENV APP_DIR=${APP_DIR}
ENV HOSTNAME=0.0.0.0
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=build --chown=nextjs:nodejs /app/apps/${APP_DIR}/.next/standalone ./
COPY --from=build --chown=nextjs:nodejs /app/apps/${APP_DIR}/.next/static ./apps/${APP_DIR}/.next/static

USER nextjs
EXPOSE 8080
CMD ["sh", "-c", "node apps/${APP_DIR}/server.js"]
